### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by petrk94** [yugasun/x-chart#3]
Hello,

I have installed it with npm and run build, but its not accessible, which "server" it need to run?

```
  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

```

**Comment by yugasun** [comment]
@petrk94 you can run `npm run dev` command.

**Comment by petrk94** [comment]
I tried, but I get this:

```
  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\views\index\index.vue:73:9
  </style>
           ^

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\views\index\index.vue:74:1

   ^


✘ 74 problems (74 errors, 0 warnings)


Errors:
  74  http://eslint.org/docs/rules/linebreak-style

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

```

but it doesnt change anything and I dont see any result coming

**Comment by yugasun** [comment]
@petrk94 Maybe you can refer to [this method](https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style-in-eslint-using)

**Comment by petrk94** [comment]
Well, I think this problem is not on mine site and more in the source code.
But even with the errors, it run and doesnt continue.

**Comment by yugasun** [comment]
As you provide errors, all of them are eslint errors `http://eslint.org/docs/rules/linebreak-style
`, so you can diasable `linebreak-style` rule and try it again.

**Comment by petrk94** [comment]
ok, but which files I have to change, change manually every file?
I just wanted to test it, but doing so much just to fix this bug is not my intention.

**Comment by yugasun** [comment]
edit `.eslintrc.js` in the project root, add `'linebreak-style': 'off',` in the rules like below:

```js
rules: {
  // ....
  'prefer-destructuring': 'off',
  // add below property
  'linebreak-style': 'off',
}
```

**Comment by petrk94** [comment]
ok thanks, now it works, but how I can use it like embed the charts in html website?
I could its very nice, but how to integrate it in any website?

**Comment by yugasun** [comment]
Sorry, it's a demo project not a npm module, before you use, you should know how to use [Vue.js](https://github.com/vuejs/vue), and just copy the chart component.

**Comment by petrk94** [comment]
hmm I see, thats bad, Im not in Vue.js, just started to learn AngularJS. But anyway, a real cool project you made :) 👍
