### ISSUE TITLE
Can I Contribute logo for x-chart ?

### ISSUE THREAD

**Issue by iqbalhood** [yugasun/x-chart#4]
Hello @yugasun. Can I Contribute to make Logo For This Project ?

**Comment by yugasun** [comment]
welcome~

**Comment by iqbalhood** [comment]
Hello @yugasun ,
These are my logo proposal for your project. If there any revision, please just tell it.

![xchart](https://user-images.githubusercontent.com/1563756/41198113-acb88316-6c9b-11e8-890f-f447f52e02f3.jpeg)

**Comment by yugasun** [comment]
@iqbalhood maybe use the four colors of the themes can be better.
